include: package:pedantic/analysis_options.yaml

analyzer:
  language:
    strict-raw-types: true
  exclude:
    - test/data/**
    - example/**
    - build/**

# Lint rules and documentation, see http://dart-lang.github.io/linter/lints
linter:
  rules:
    - always_declare_return_types
    - avoid_empty_else
    - avoid_init_to_null
    - avoid_print
    - avoid_relative_lib_imports
    - avoid_return_types_on_setters
    - avoid_types_as_parameter_names
    - camel_case_types
    - cancel_subscriptions
    - constant_identifier_names
    - empty_constructor_bodies
    - hash_and_equals
    - implementation_imports
    - iterable_contains_unrelated_type
    - library_names
    - library_prefixes
    - list_remove_unrelated_type
    - no_duplicate_case_values
    - non_constant_identifier_names
    - null_closures
    - one_member_abstracts
    - package_api_docs
    - package_names
    - package_prefixed_library_names
    - prefer_contains
    - prefer_equal_for_default_values
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_single_quotes
    - recursive_getters
    - slash_for_doc_comments
    - test_types_in_equals
    - type_init_formals
    - unawaited_futures
    - unnecessary_const
    - unnecessary_getters_setters
    - unnecessary_new
    - unrelated_type_equality_checks
    - use_rethrow_when_possible
    - valid_regexps
