name: json_serializable_generator
description: This generator creates a safe way to serialize and deserialize json strings using a simple JSON schema.
homepage: https://github.com/dweiss96/json_serializable_generator
repository: https://github.com/dweiss96/json_serializable_generator/tree/master
issues: https://github.com/dweiss96/json_serializable_generator/issues
version: 1.0.0-rc2

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  build: ^1.2.2
  meta: ^1.1.8

dev_dependencies:
  build_runner: ^1.7.4
  build_test: ^0.10.12+1
  pedantic: ^1.8.0
  test: ^1.6.4
