name: json_serializable_generator
description: This generator creates a safe way to serialize and deserialize json strings using a simple JSON schema.
homepage: https://github.com/dweiss96/json_serializable_generator
repository: https://github.com/dweiss96/json_serializable_generator/tree/master
issues: https://github.com/dweiss96/json_serializable_generator/issues
version: 1.0.1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  build: ^2.4.1
  meta: ^1.1.8

dev_dependencies:
  build_runner: ^2.4.6
  build_test: ^2.2.1
  pedantic: ^1.8.0
  test: ^1.6.4
